INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)
VALUES ('BUILDINGS','GEO',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',0,250,1),MDSYS.SDO_DIM_ELEMENT('Y',0,250,1)),NULL);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)
VALUES ('ROADS','GEO',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',0,250,1),MDSYS.SDO_DIM_ELEMENT('Y',0,250,1)),NULL);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)
VALUES ('NATURE','GEO',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',0,250,1),MDSYS.SDO_DIM_ELEMENT('Y',0,250,1)),NULL);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)
VALUES ('ANIMALS','GEO',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',0,250,1),MDSYS.SDO_DIM_ELEMENT('Y',0,250,1)),NULL);

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID)
VALUES ('VEHICLES','GEO',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',0,250,1),MDSYS.SDO_DIM_ELEMENT('Y',0,250,1)),NULL);




