drop table buildings_info;
drop table buildings;
drop table roads_info;
drop table roads;
drop table nature;
drop table animals_info;
drop table animals;
drop table vehicles_info;
drop table vehicles;

DROP SEQUENCE SEQ_BUILDINGS;
DROP SEQUENCE SEQ_ROADS;
DROP SEQUENCE SEQ_NATURE;
DROP SEQUENCE SEQ_ANIMALS;
DROP SEQUENCE SEQ_VEHICLES;

CREATE TABLE BUILDINGS (
    BUILDING_ID INT PRIMARY KEY,
    BUILDING_TYPE VARCHAR(50),
    GEO MDSYS.SDO_GEOMETRY
);

CREATE TABLE BUILDINGS_INFO (
    BUILDING_ID INT PRIMARY KEY,
    OWNER_NAME VARCHAR(50),
    CONSTRUCTION_DATE DATE,
    DESCRIPTION VARCHAR(500),
    FOREIGN KEY (BUILDING_ID) REFERENCES BUILDINGS (BUILDING_ID)
);

CREATE TABLE ROADS (
    ROAD_ID INT PRIMARY KEY,
    ROAD_TYPE VARCHAR(50),
    GEO MDSYS.SDO_GEOMETRY
);

CREATE TABLE ROADS_INFO (
    ROAD_ID INT PRIMARY KEY,
    ROAD_STATUS VARCHAR(50),
    LAST_CHECK_DATE DATE,
    DESCRIPTION VARCHAR(500),
    FOREIGN KEY (ROAD_ID) REFERENCES ROADS (ROAD_ID)
);

CREATE TABLE NATURE (
    NATURE_ID INT PRIMARY KEY,
    NATURE_TYPE VARCHAR(50),
    GEO MDSYS.SDO_GEOMETRY
);

CREATE TABLE ANIMALS (
    ANIMAL_ID INT PRIMARY KEY,
    ANIMAL_TYPE VARCHAR(50),
    GEO MDSYS.SDO_GEOMETRY
);

CREATE TABLE ANIMALS_INFO (
    ANIMAL_ID INT PRIMARY KEY,
    OWNER_NAME VARCHAR(50),
    DATE_OF_BIRTH DATE,
    FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMALS (ANIMAL_ID)
);

CREATE TABLE VEHICLES (
    VEHICLE_ID INT PRIMARY KEY,
    VEHICLE_TYPE VARCHAR(50),
    GEO MDSYS.SDO_GEOMETRY
);

CREATE TABLE VEHICLES_INFO (
    VEHICLE_ID INT PRIMARY KEY,
    OWNER_NAME VARCHAR(50),
    LAST_CHECK DATE,
    DISTANCE_KM INT,
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLES (VEHICLE_ID)
);


CREATE SEQUENCE SEQ_BUILDINGS;
CREATE SEQUENCE SEQ_ROADS;
CREATE SEQUENCE SEQ_NATURE;
CREATE SEQUENCE SEQ_ANIMALS;
CREATE SEQUENCE SEQ_VEHICLES;


