-- LIMITS
INSERT INTO spatial_data (id, geometry)
SELECT 1, MDSYS.SDO_GEOMETRY(2001, NULL, MDSYS.SDO_POINT_TYPE(0, 0, NULL), NULL, NULL) FROM DUAL UNION ALL
SELECT 2, MDSYS.SDO_GEOMETRY(2001, NULL, MDSYS.SDO_POINT_TYPE(0, 250, NULL), NULL, NULL) FROM DUAL UNION ALL
SELECT 3, MDSYS.SDO_GEOMETRY(2001, NULL, MDSYS.SDO_POINT_TYPE(250, 250, NULL), NULL, NULL) FROM DUAL UNION ALL
SELECT 4, MDSYS.SDO_GEOMETRY(2001, NULL, MDSYS.SDO_POINT_TYPE(250, 0, NULL), NULL, NULL) FROM DUAL;

INSERT INTO spatial_data (id, geometry)
VALUES (
    15,  
    MDSYS.SDO_GEOMETRY(
        2003,
        NULL,
        NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
         MDSYS.SDO_ORDINATE_ARRAY(90,40, 90,260, 260,260, 260,40, 90,40)
    )
);

-- DROP
DELETE FROM spatial_data;
DELETE FROM BUILDINGS;
DELETE FROM ROADS;
DELETE FROM NATURE;
DELETE FROM ANIMALS;
DELETE FROM VEHICLES;

DELETE FROM BUILDINGS_INFO;
DELETE FROM ROADS_INFO;
DELETE FROM ANIMALS_INFO;
DELETE FROM VEHICLES_INFO;

-- BUILDINGS
-- House
INSERT INTO BUILDINGS (BUILDING_ID, BUILDING_TYPE, GEO) 
VALUES (
    SEQ_BUILDINGS.nextval,
    'House', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1), 
                        MDSYS.SDO_ORDINATE_ARRAY(150,107.5, 120,107.5, 120,175, 150,175, 150,107.5))
);
-- Watermill
INSERT INTO BUILDINGS (BUILDING_ID, BUILDING_TYPE, GEO) 
VALUES (
    SEQ_BUILDINGS.nextval,
    'Watermill', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1), 
                        MDSYS.SDO_ORDINATE_ARRAY(72,210, 40,140, 30,190, 72,210))
);

-- Shop
INSERT INTO BUILDINGS (BUILDING_ID, BUILDING_TYPE, GEO) 
VALUES (
    SEQ_BUILDINGS.nextval,
    'Shop', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1), 
                        MDSYS.SDO_ORDINATE_ARRAY(150,72.5, 210,72.5, 210,40, 150,40, 150,72.5))
);

-- ROADS
-- Principal road
INSERT INTO ROADS (ROAD_ID, ROAD_TYPE, GEO) 
VALUES (
    SEQ_ROADS.nextval,
    'Road', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1), 
                        MDSYS.SDO_ORDINATE_ARRAY(0,75, 250,75, 250,90, 0,90, 0,75))
);
-- Curved road
INSERT INTO ROADS (ROAD_ID, ROAD_TYPE, GEO) 
VALUES (
    SEQ_ROADS.nextval,
    'Road', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,5,4, 1,2,1, 3,2,2, 7,2,1, 9,2,2),
                        MDSYS.SDO_ORDINATE_ARRAY(100,75, 110,75, 120,50, 130,0, 120,0, 110,50, 100,75))
);
-- Vertical road
INSERT INTO ROADS (ROAD_ID, ROAD_TYPE, GEO) 
VALUES (
    SEQ_ROADS.nextval,
    'Road', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1), 
                        MDSYS.SDO_ORDINATE_ARRAY(180,90, 190,90, 190,250, 180,250, 180,90))
);
-- Path to road to house
INSERT INTO ROADS (ROAD_ID, ROAD_TYPE, GEO) 
VALUES (
    SEQ_ROADS.nextval,
    'Path', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1), 
                        MDSYS.SDO_ORDINATE_ARRAY(180,142.5, 180,147.5, 150,147.5, 150,142.5, 180,142.5))
);



-- NATURE
-- Bottom left lake
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO) 
VALUES (
    SEQ_NATURE.nextval,
    'Lake', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,5,4, 1,2,1, 3,2,2, 7,2,1, 9,2,2),
                        MDSYS.SDO_ORDINATE_ARRAY(10,50, 45,65, 90,50, 90,10, 45,5, 10,10, 10,50))
);
-- Field top right
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO) 
VALUES (
    SEQ_NATURE.nextval,
    'Field', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1), 
                        MDSYS.SDO_ORDINATE_ARRAY(200,110, 250,110, 250,250, 200,250, 200,110))
);
-- Field of animal
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO) 
VALUES (
    SEQ_NATURE.nextval,
    'Animal Field', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,3,1), 
                        MDSYS.SDO_ORDINATE_ARRAY(170,180, 170,240, 100,240, 100,180, 170,180))
);

-- River
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO) 
VALUES (
    SEQ_NATURE.nextval,
    'River', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,5,4, 1,2,1, 3,2,2, 7,2,1, 9,2,2),
                        MDSYS.SDO_ORDINATE_ARRAY(90,250, 70,250, 50,150, 0,115, 0,95, 70,150, 90,250))
);
-- Field bottom right
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO) 
VALUES (
    SEQ_NATURE.nextval,
    'Field', 
    MDSYS.SDO_GEOMETRY(2003, 
                        NULL, 
                        NULL, 
                        MDSYS.SDO_ELEM_INFO_ARRAY(1,3,1), 
                        MDSYS.SDO_ORDINATE_ARRAY(135,35, 215,35, 215,70, 250,70, 250,0, 135,0, 135,35))
);

INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO)
VALUES (SEQ_NATURE.NEXTVAL,
        'Tree',
        MDSYS.SDO_GEOMETRY(2001,NULL,
        MDSYS.SDO_POINT_TYPE(20,100,NULL),NULL,NULL)
);  
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO)
VALUES (SEQ_NATURE.NEXTVAL,
        'Tree',
        MDSYS.SDO_GEOMETRY(2001,NULL,
        MDSYS.SDO_POINT_TYPE(40,100,NULL),NULL,NULL)
);  
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO)
VALUES (SEQ_NATURE.NEXTVAL,
        'Tree',
        MDSYS.SDO_GEOMETRY(2001,NULL,
        MDSYS.SDO_POINT_TYPE(60,100,NULL),NULL,NULL)
);  
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO)
VALUES (SEQ_NATURE.NEXTVAL,
        'Tree',
        MDSYS.SDO_GEOMETRY(2001,NULL,
        MDSYS.SDO_POINT_TYPE(80,100,NULL),NULL,NULL)
);  
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO)
VALUES (SEQ_NATURE.NEXTVAL,
        'Tree',
        MDSYS.SDO_GEOMETRY(2001,NULL,
        MDSYS.SDO_POINT_TYPE(100,100,NULL),NULL,NULL)
);  
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO)
VALUES (SEQ_NATURE.NEXTVAL,
        'Tree',
        MDSYS.SDO_GEOMETRY(2001,NULL,
        MDSYS.SDO_POINT_TYPE(60,120,NULL),NULL,NULL)
);  
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO)
VALUES (SEQ_NATURE.NEXTVAL,
        'Tree',
        MDSYS.SDO_GEOMETRY(2001,NULL,
        MDSYS.SDO_POINT_TYPE(80,120,NULL),NULL,NULL)
);  
INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO)
VALUES (SEQ_NATURE.NEXTVAL,
        'Tree',
        MDSYS.SDO_GEOMETRY(2001,NULL,
        MDSYS.SDO_POINT_TYPE(80,140,NULL),NULL,NULL)
); 

-- Forest on the left
CREATE OR REPLACE PROCEDURE ADD_TREES_ALONG_AXIS_X(
    p_start_y NUMBER,
    p_end_y NUMBER,
    p_spacing NUMBER
)
IS
    v_current_y NUMBER := p_start_y;
BEGIN
    -- Add trees along x=0
    WHILE v_current_y <= p_end_y
    LOOP
        INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO)
        VALUES (SEQ_NATURE.NEXTVAL,
                'Tree',
                MDSYS.SDO_GEOMETRY(2001, NULL,
                                   MDSYS.SDO_POINT_TYPE(0, v_current_y, NULL),
                                   NULL, NULL)
                );

        v_current_y := v_current_y + p_spacing;
    END LOOP;

    -- Re initialize y value
    v_current_y := p_start_y;

    -- add trees along x=20
    WHILE v_current_y <= p_end_y
    LOOP
        INSERT INTO NATURE (NATURE_ID, NATURE_TYPE, GEO)
        VALUES (SEQ_NATURE.NEXTVAL,
                'Tree',
                MDSYS.SDO_GEOMETRY(2001, NULL,
                                   MDSYS.SDO_POINT_TYPE(20, v_current_y, NULL),
                                   NULL, NULL)
                );

        v_current_y := v_current_y + p_spacing;
    END LOOP;
END ADD_TREES_ALONG_AXIS_X;
/
BEGIN
    ADD_TREES_ALONG_AXIS_X(130, 250, 20);
END;
/


-- ANIMALS
INSERT INTO ANIMALS (ANIMAL_ID, ANIMAL_TYPE, GEO)
VALUES (SEQ_ANIMALS.nextval, 'Cow', MDSYS.SDO_GEOMETRY(2003, NULL, NULL, 
        MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(110, 200, 115, 200, 115, 205, 110, 205, 110, 200)));

INSERT INTO ANIMALS (ANIMAL_ID, ANIMAL_TYPE, GEO)
VALUES (SEQ_ANIMALS.nextval, 'Cow', MDSYS.SDO_GEOMETRY(2003, NULL, NULL, 
        MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(120, 190, 125, 190, 125, 195, 120, 195, 120, 190)));

INSERT INTO ANIMALS (ANIMAL_ID, ANIMAL_TYPE, GEO)
VALUES (SEQ_ANIMALS.nextval, 'Cow', 
        MDSYS.SDO_GEOMETRY(2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(130, 200, 135, 200, 135, 205, 130, 205, 130, 200)));

INSERT INTO ANIMALS (ANIMAL_ID, ANIMAL_TYPE, GEO)
VALUES (SEQ_ANIMALS.nextval, 'Cow', 
        MDSYS.SDO_GEOMETRY(2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(140, 190, 145, 190, 145, 195, 140, 195, 140, 190)));

INSERT INTO ANIMALS (ANIMAL_ID, ANIMAL_TYPE, GEO)
VALUES (SEQ_ANIMALS.nextval, 'Cow', 
        MDSYS.SDO_GEOMETRY(2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(150, 200, 155, 200, 155, 205, 150, 205, 150, 200)));

INSERT INTO ANIMALS (ANIMAL_ID, ANIMAL_TYPE, GEO)
VALUES (SEQ_ANIMALS.nextval, 'Sheep', 
        MDSYS.SDO_GEOMETRY(2007, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(120, 215, 120, 220, 125, 217.5, 120, 215)));

INSERT INTO ANIMALS (ANIMAL_ID, ANIMAL_TYPE, GEO)
VALUES (SEQ_ANIMALS.nextval, 'Sheep', 
        MDSYS.SDO_GEOMETRY(2007, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(130, 215, 130, 220, 135, 217.5, 130, 215)));

INSERT INTO ANIMALS (ANIMAL_ID, ANIMAL_TYPE, GEO)
VALUES (SEQ_ANIMALS.nextval, 'Sheep', 
        MDSYS.SDO_GEOMETRY(2007, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(140, 215, 140, 220, 145, 217.5, 140, 215)));

INSERT INTO ANIMALS (ANIMAL_ID, ANIMAL_TYPE, GEO)
VALUES (SEQ_ANIMALS.nextval, 'Sheep', 
        MDSYS.SDO_GEOMETRY(2007, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(150, 215, 150, 220, 155, 217.5, 150, 215)));

INSERT INTO ANIMALS (ANIMAL_ID, ANIMAL_TYPE, GEO)
VALUES (SEQ_ANIMALS.nextval, 'Sheep', 
        MDSYS.SDO_GEOMETRY(2007, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(150,225, 150,230, 155,227.5, 150,225)));

INSERT INTO ANIMALS (ANIMAL_ID, ANIMAL_TYPE, GEO)
VALUES (SEQ_ANIMALS.nextval, 'Sheep', 
        MDSYS.SDO_GEOMETRY(2007, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(140, 225, 140, 230, 145, 227.5, 140, 225)));

-- VEHICLES
INSERT INTO VEHICLES (VEHICLE_ID, VEHICLE_TYPE, GEO)
VALUES (SEQ_VEHICLES.nextval, 'Car', 
        MDSYS.SDO_GEOMETRY(2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(155,175, 175,175, 175,165, 155,165, 155,175)));

INSERT INTO VEHICLES (VEHICLE_ID, VEHICLE_TYPE, GEO)
VALUES (SEQ_VEHICLES.nextval, 'Car', 
        MDSYS.SDO_GEOMETRY(2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(155,160, 175,160, 175,150, 155,150, 155,160)));

INSERT INTO VEHICLES (VEHICLE_ID, VEHICLE_TYPE, GEO)
VALUES (SEQ_VEHICLES.nextval, 'Car', 
        MDSYS.SDO_GEOMETRY(2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(155,140, 175,140, 175,130, 155,130, 155,140)));

INSERT INTO VEHICLES (VEHICLE_ID, VEHICLE_TYPE, GEO)
VALUES (SEQ_VEHICLES.nextval, 'Car', 
        MDSYS.SDO_GEOMETRY(2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(155,125, 175,125, 175,115, 155,115, 155,125)));

INSERT INTO VEHICLES (VEHICLE_ID, VEHICLE_TYPE, GEO)
VALUES (SEQ_VEHICLES.nextval, 'Tractor', 
        MDSYS.SDO_GEOMETRY(2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(117.5,175, 100,175, 100,147.5, 117.5,147.5, 117.5,175)));

INSERT INTO VEHICLES (VEHICLE_ID, VEHICLE_TYPE, GEO)
VALUES (SEQ_VEHICLES.nextval, 'Tractor', 
        MDSYS.SDO_GEOMETRY(2003, NULL, NULL, MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 1), MDSYS.SDO_ORDINATE_ARRAY(117.5,142.5, 100,142.5, 100,115, 117.5,115, 117.5,142.5)));




--BUILDINGS INFO
-- House Info
INSERT INTO BUILDINGS_INFO (BUILDING_ID, OWNER_NAME, CONSTRUCTION_DATE, DESCRIPTION)
VALUES (
    (SELECT BUILDING_ID FROM BUILDINGS WHERE BUILDING_TYPE = 'House'),
    'John Smith', 
    TO_DATE('2023-01-01', 'YYYY-MM-DD'),
    'Cozy family home with a beautiful garden and modern amenities.'
);
-- Watermill Info
INSERT INTO BUILDINGS_INFO (BUILDING_ID, OWNER_NAME, CONSTRUCTION_DATE, DESCRIPTION)
VALUES (
    (SELECT BUILDING_ID FROM BUILDINGS WHERE BUILDING_TYPE = 'Watermill'),
    'Jane Doe',
    TO_DATE('2023-02-01', 'YYYY-MM-DD'),
    'Picturesque watermill by the river, perfect for a serene retreat.'
);
-- Shop Info
INSERT INTO BUILDINGS_INFO (BUILDING_ID, OWNER_NAME, CONSTRUCTION_DATE, DESCRIPTION)
VALUES (
    (SELECT BUILDING_ID FROM BUILDINGS WHERE BUILDING_TYPE = 'Shop'),
    'Bob Johnson', 
    TO_DATE('2023-03-01', 'YYYY-MM-DD'),
    'Corner shop offering a variety of goods, friendly service, and local charm.'
);

-- ROADS INFO
-- Principal Road Info
INSERT INTO ROADS_INFO (ROAD_ID, ROAD_STATUS, LAST_CHECK_DATE, DESCRIPTION)
VALUES (
    1, 
    'Open',
    TO_DATE('2023-01-01', 'YYYY-MM-DD'),
    'Main road connecting key areas with smooth traffic flow.'
);
-- Curved Road Info (Closed)
INSERT INTO ROADS_INFO (ROAD_ID, ROAD_STATUS, LAST_CHECK_DATE, DESCRIPTION)
VALUES (
    2, 
    'Closed',
    TO_DATE('2023-01-02', 'YYYY-MM-DD'),
    'Curved road currently closed for maintenance, use alternative routes.'
);
-- Vertical Road Info
INSERT INTO ROADS_INFO (ROAD_ID, ROAD_STATUS, LAST_CHECK_DATE, DESCRIPTION)
VALUES (
    3, 
    'Open',
    TO_DATE('2023-01-03', 'YYYY-MM-DD'),
    'Vertical road facilitating north-south traffic in the city.'
);
-- Path to Road to House Info
INSERT INTO ROADS_INFO (ROAD_ID, ROAD_STATUS, LAST_CHECK_DATE, DESCRIPTION)
VALUES (
    4, 
    'Open',
    TO_DATE('2023-01-04', 'YYYY-MM-DD'),
    'Path leading from the main road to a residential house.'
);

-- ANIMALS INFO
-- Cow Info
INSERT INTO ANIMALS_INFO (ANIMAL_ID, OWNER_NAME, DATE_OF_BIRTH)
VALUES (1, 'Johnson Family', TO_DATE('2020-05-01', 'YYYY-MM-DD'));

INSERT INTO ANIMALS_INFO (ANIMAL_ID, OWNER_NAME, DATE_OF_BIRTH)
VALUES (2, 'Johnson Family', TO_DATE('2020-06-15', 'YYYY-MM-DD'));

INSERT INTO ANIMALS_INFO (ANIMAL_ID, OWNER_NAME, DATE_OF_BIRTH)
VALUES (3, 'Johnson Family', TO_DATE('2020-08-10', 'YYYY-MM-DD'));

INSERT INTO ANIMALS_INFO (ANIMAL_ID, OWNER_NAME, DATE_OF_BIRTH)
VALUES (4, 'Johnson Family', TO_DATE('2020-09-20', 'YYYY-MM-DD'));

INSERT INTO ANIMALS_INFO (ANIMAL_ID, OWNER_NAME, DATE_OF_BIRTH)
VALUES (5, 'Johnson Family', TO_DATE('2021-01-05', 'YYYY-MM-DD'));

-- Sheep Info
INSERT INTO ANIMALS_INFO (ANIMAL_ID, OWNER_NAME, DATE_OF_BIRTH)
VALUES (6, 'Smith Family', TO_DATE('2019-12-01', 'YYYY-MM-DD'));

INSERT INTO ANIMALS_INFO (ANIMAL_ID, OWNER_NAME, DATE_OF_BIRTH)
VALUES (7, 'Smith Family', TO_DATE('2020-02-15', 'YYYY-MM-DD'));

INSERT INTO ANIMALS_INFO (ANIMAL_ID, OWNER_NAME, DATE_OF_BIRTH)
VALUES (8, 'Smith Family', TO_DATE('2020-04-10', 'YYYY-MM-DD'));

INSERT INTO ANIMALS_INFO (ANIMAL_ID, OWNER_NAME, DATE_OF_BIRTH)
VALUES (9, 'Smith Family', TO_DATE('2020-06-20', 'YYYY-MM-DD'));

INSERT INTO ANIMALS_INFO (ANIMAL_ID, OWNER_NAME, DATE_OF_BIRTH)
VALUES (10, 'Smith Family', TO_DATE('2020-09-05', 'YYYY-MM-DD'));

INSERT INTO ANIMALS_INFO (ANIMAL_ID, OWNER_NAME, DATE_OF_BIRTH)
VALUES (11, 'Smith Family', TO_DATE('2020-10-01', 'YYYY-MM-DD'));

-- VEHICLES INFO
-- Car Info
INSERT INTO VEHICLES_INFO (VEHICLE_ID, OWNER_NAME, LAST_CHECK, DISTANCE_KM)
VALUES (1, 'Johnson Family', TO_DATE('2022-01-15', 'YYYY-MM-DD'), 5000);

INSERT INTO VEHICLES_INFO (VEHICLE_ID, OWNER_NAME, LAST_CHECK, DISTANCE_KM)
VALUES (2, 'Johnson Family', TO_DATE('2022-02-20', 'YYYY-MM-DD'), 6000);

INSERT INTO VEHICLES_INFO (VEHICLE_ID, OWNER_NAME, LAST_CHECK, DISTANCE_KM)
VALUES (3, 'Johnson Family', TO_DATE('2022-03-10', 'YYYY-MM-DD'), 4500);

INSERT INTO VEHICLES_INFO (VEHICLE_ID, OWNER_NAME, LAST_CHECK, DISTANCE_KM)
VALUES (4, 'Johnson Family', TO_DATE('2022-04-05', 'YYYY-MM-DD'), 5500);

-- Tractor Info
INSERT INTO VEHICLES_INFO (VEHICLE_ID, OWNER_NAME, LAST_CHECK, DISTANCE_KM)
VALUES (5, 'Smith Family', TO_DATE('2022-02-15', 'YYYY-MM-DD'), 3000);

INSERT INTO VEHICLES_INFO (VEHICLE_ID, OWNER_NAME, LAST_CHECK, DISTANCE_KM)
VALUES (6, 'Smith Family', TO_DATE('2022-03-20', 'YYYY-MM-DD'), 2500);

SELECT *
FROM BUILDINGS
JOIN BUILDINGS_INFO ON BUILDINGS.BUILDING_ID = BUILDINGS_INFO.BUILDING_ID;

SELECT *
FROM ROADS
JOIN ROADS_INFO ON ROADS.ROAD_ID = ROADS_INFO.ROAD_ID;

select * from nature;

SELECT *
FROM ANIMALS
JOIN ANIMALS_INFO ON ANIMALS.ANIMAL_ID = ANIMALS_INFO.ANIMAL_ID;

SELECT *
FROM VEHICLES
JOIN VEHICLES_INFO ON VEHICLES.VEHICLE_ID = VEHICLES_INFO.VEHICLE_ID;




