CREATE INDEX idx_buildings_geo ON BUILDINGS(GEO) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX idx_roads_geo ON ROADS(GEO) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX idx_nature_geo ON NATURE(GEO) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX idx_animals_geo ON ANIMALS(GEO) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX idx_vehicles_geo ON VEHICLES(GEO) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME, SDO_INDEX_TYPE
FROM ALL_SDO_INDEX_INFO;
