-- a : nb cows per field
SELECT
    N.NATURE_ID,
    N.NATURE_TYPE,
    FLOOR(SDO_GEOM.SDO_AREA(N.GEO, 0.005) / 9) AS NUM_COWS_IN_FIELD
FROM
    NATURE N
WHERE
    N.NATURE_TYPE = 'Field'; 

-- b aera total of jonhson
SELECT
    SUM(TOTAL_AREA) AS TOTAL_AREA
FROM (
    SELECT
        NVL(SUM(SDO_GEOM.SDO_AREA(B.GEO, 0.005)), 0) AS TOTAL_AREA
    FROM
        BUILDINGS B
    LEFT JOIN
        BUILDINGS_INFO BI ON B.BUILDING_ID = BI.BUILDING_ID
    WHERE
        BI.OWNER_NAME LIKE '%Johnson%'
    UNION
    SELECT
        NVL(SUM(SDO_GEOM.SDO_AREA(V.GEO, 0.005)), 0) AS TOTAL_AREA
    FROM
        VEHICLES V
    LEFT JOIN
        VEHICLES_INFO VI ON V.VEHICLE_ID = VI.VEHICLE_ID
    WHERE
        VI.OWNER_NAME LIKE '%Johnson%'
) RESULT;

-- c : intersection zone
SELECT  N.NATURE_TYPE AS OBJECT_NAME
    FROM
        NATURE N
    WHERE
        SDO_INSIDE(N.GEO, MDSYS.SDO_GEOMETRY(2003,NULL,NULL,
                            MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
                            MDSYS.SDO_ORDINATE_ARRAY(90,40, 90,260, 260,260, 260,40, 90,40))) = 'TRUE'
UNION
                            
SELECT  B.BUILDING_TYPE AS OBJECT_NAME
    FROM
        BUILDINGS B
    WHERE
        SDO_INSIDE(B.GEO, MDSYS.SDO_GEOMETRY(2003,NULL,NULL,
                            MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
                            MDSYS.SDO_ORDINATE_ARRAY(90,40, 90,260, 260,260, 260,40, 90,40))) = 'TRUE'
UNION
                            
SELECT  V.VEHICLE_TYPE AS OBJECT_NAME
    FROM
        VEHICLES V
    WHERE
        SDO_INSIDE(V.GEO, MDSYS.SDO_GEOMETRY(2003,NULL,NULL,
                            MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
                            MDSYS.SDO_ORDINATE_ARRAY(90,40, 90,260, 260,260, 260,40, 90,40))) = 'TRUE'
UNION

SELECT  R.ROAD_TYPE AS OBJECT_NAME
    FROM
        ROADS R
    WHERE
        SDO_INSIDE(R.GEO, MDSYS.SDO_GEOMETRY(2003,NULL,NULL,
                            MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
                            MDSYS.SDO_ORDINATE_ARRAY(90,40, 90,260, 260,260, 260,40, 90,40))) = 'TRUE'
UNION

SELECT  A.ANIMAL_TYPE AS OBJECT_NAME
    FROM
        ANIMALS A
    WHERE
        SDO_INSIDE(A.GEO, MDSYS.SDO_GEOMETRY(2003,NULL,NULL,
                            MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,1),
                            MDSYS.SDO_ORDINATE_ARRAY(90,40, 90,260, 260,260, 260,40, 90,40))) = 'TRUE';

-- d 
SELECT
    B.BUILDING_ID,
    B.BUILDING_TYPE,
    L.NATURE_ID AS LAKE_ID,
    L.NATURE_TYPE,
    ROUND(SDO_NN_DISTANCE(1), 2) AS DISTANCE
FROM
    BUILDINGS B
    JOIN NATURE L ON L.NATURE_TYPE = 'Lake'
WHERE
    SDO_NN(B.GEO, L.GEO, 'sdo_batch_size=10', 1) = 'TRUE'
ORDER BY
    SDO_NN_DISTANCE(1)
FETCH FIRST 1 ROW ONLY;

-- e
SELECT
    B.BUILDING_ID AS BUILDING_ID,
    B.BUILDING_TYPE AS BUILDING_TYPE,
    R.ROAD_ID AS ROAD_ID,
    R.ROAD_TYPE AS ROAD_TYPE
FROM
    BUILDINGS B
    JOIN ROADS R ON SDO_RELATE(B.GEO, R.GEO, 'mask=TOUCH') = 'TRUE';
    
SELECT
    B.BUILDING_ID AS BUILDING_ID,
    B.BUILDING_TYPE AS BUILDING_TYPE,
    R.ROAD_ID AS ROAD_ID,
    R.ROAD_TYPE AS ROAD_TYPE
FROM
    BUILDINGS B
    JOIN ROADS R ON SDO_ANYINTERACT(B.GEO, R.GEO) = 'TRUE';

-- f
SELECT
    COUNT(*) AS ANIMAL_COUNT
FROM
    ANIMALS A
WHERE
    SDO_FILTER(A.GEO,
            (SELECT GEO FROM NATURE WHERE NATURE_TYPE = 'Animal Field')) = 'TRUE';


